import { type Plan } from '@campus/contracts';

import { type MediaSource } from '@/lib/hero-media';

/**
 * Plan card photos (B4: 4:5), keyed by the plan's `imageId`. Generated by
 * `scripts/placeholders.mjs`.
 * TODO(client): real photos and usage rights (docs/09-roadmap.md #3); swap the files and alt here.
 */
const PLAN_PHOTOS: Readonly<Record<string, MediaSource>> = Object.fromEntries(
  [
    'plan-hot-desk',
    'plan-business-seating',
    'plan-executive-seating',
    'plan-private-office',
    'plan-meeting-room',
    'plan-seminar-room',
  ].map((id) => [id, { src: `/placeholder/${id}.jpg`, width: 960, height: 1200 }]),
);

export interface PlanPhoto extends MediaSource {
  alt: string;
}

/**
 * The photo for a plan card, or `undefined` when its `imageId` has no file yet (a plan added in
 * the admin), so the card shows its empty frame instead of a broken image.
 */
export function planPhoto(plan: Pick<Plan, 'imageId' | 'name'>): PlanPhoto | undefined {
  const photo = PLAN_PHOTOS[plan.imageId];
  return photo ? { ...photo, alt: `Placeholder photo: ${plan.name}` } : undefined;
}
